### ISSUE TITLE
Auto Queue cannot be enabled with alt + left click, but alt + right click works

### ISSUE THREAD

**Issue by rlesko** [Resike/TrinketMenu#11]
This was working fine prior to update. Trying to determine if something is wrong with my local set up or if its the add on. It seems like the callback function TrinketMenu.MainTrinket_OnClick() is somehow getting called twice, resulting in the trinket toggle getting enabled and disabled per click

**Comment by rlesko** [comment]
Was testing on classic era. Also a guildie confirmed he experienced the same issue.

**Comment by rlesko** [comment]
Through some very rudimentary debugging I think the issue could be the fact that the function is being registered with the PostClick handler in the xml file. It looks like the callback fires for both down and up. 

https://wowpedia.fandom.com/wiki/UIHANDLER_PostClick

I have a hack locally but I'm sure its not a clean solution. But seems like button and down can be added to the `MainTrinket_OnClick()` function signature to only toggle on a `down` or `up` event.

**Comment by Resike** [comment]
Fixed
