### ISSUE TITLE
Broken features on 10.0.2 for the 1.14.4 client. 

### ISSUE THREAD

**Issue by Theguyxd** [Resike/TrinketMenu#13]
I have seen some people bring this up already but I thought I'd add to the current list of issues as of right now. These issues have only been tested on the Classic Era Hardcore servers with the addon 10.0.2 for the 1.14.4 client.

Clicking the TrinketMenu to queue another trinket to be equipped as soon as combat ends currently does not work. It simply does nothing if you try and swap in combat. 

Second issue. The "notify me when trinket is ready" and "notify me when there 30 seconds left" does not work either. They send no message when either of these conditions are met.

**Comment by Resike** [comment]
Fixed.
