### ISSUE TITLE
Merging of codebases

### ISSUE THREAD

**Issue by Nixxen** [Resike/TrinketMenu#3]
Hey Resike!

I did some fixes to TrinketMenu to make it compatible with Classic when Classic released a while back. I tried contacting Gello on Curse, but never heard back from him.
I didn't realize the addon was still in development. If you want to you can use the work we've done on it so far, and merge it with this version (I assume this is the "official one"?).
In that case we could redirect all the issues / ideas to one place, and I could update the "Classic" repo with a link to this one.

https://github.com/Nixxen/TrinketMenu

**Comment by Resike** [comment]
Yeah I can push released for the project but I'm not the owner, every tag from here gets pushed to Curse. The addon is not really in development, just in a maintainment mode, I think it works nicely now with every clients, but if you can issue new PRs here if you have a fix for something.
